version: "2.1"
services:
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: ${PROJECT_ROOT}/.docksal/services/cli
    volumes:
      - culturelle_drupal_composer_packages:/var/www/vendor
      - culturelle_drupal_contrib:/var/www/web/modules/composer
    environment:
      - DOCKSAL_ENV=true
      - DRUSH_OPTIONS_URI=${VIRTUAL_HOST}
      - "XDEBUG_CONFIG=client_host=${DOCKSAL_HOST_IP} client_port=9000"
      - "XDEBUG_MODE=debug,develop"
      - "COMPOSER_MEMORY_LIMIT=-1"
  varnish:
    labels:
      - io.docksal.virtual-host=varnish.${VIRTUAL_HOST},varnish.${VIRTUAL_HOST}.*,www.varnish.${VIRTUAL_HOST},www.varnish.${VIRTUAL_HOST}.*
  solr:
    image: docksal/solr:8.1
volumes:
  culturelle_drupal_composer_packages:
  culturelle_drupal_contrib:
